version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3001:3001"

    depends_on:
      - database

  database:
    image: postgres:14
    restart: always
    ports:
      - "5555:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pthdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
