version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pthdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pthdb
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db-data:
